name: CI / CD

on:
  push:
    branches: [ master ]

env:
  REGION: southamerica-east1

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }} ./server
          gcloud config set run/region ${{ env.REGION }}

      - name: Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          flags: '--port=3000'
          image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}:latest
          service: ${{ secrets.GCP_APP_NAME }}
          region: ${{ env.REGION }}